on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: 'test yml'
        run: pwd 

      - name: 'test print'  
        run : echo moelserougy 

      - uses: actions/checkout@v3
      - name: 'print file'  
        run : ls 


      - name: 'login to dockerhub'
        run : docker login --username ${{ secrets.USER_NAME }} --password ${{ secrets.ACCESS_TOKEN }}

      - name: 'build docker image' 
        run: docker build -t ${{ secrets.USER_NAME }}/new_image .

      - name: 'push docker image'
        run : docker push ${{ secrets.USER_NAME }}/new_image   